---
  kind: pipeline
  type: docker
  
  steps:
    - name: release_dev
      image: plugins/docker
      when:
        branch:
          - master
        event:
          - push
      settings:
        repo: registry.km8.es/svelte-adminlte
        registry: registry.km8.es
        username:
          from_secret: docker_repo_user
        password:
          from_secret: docker_repo_password
  
    - name: deploy_dev
      image: appleboy/drone-ssh
      when:
        branch:
          - master
        event:
          - push
      settings:
        host: 10.0.0.9
        port: 22
        username:
          from_secret: web-01_ssh_user
        key:
          from_secret: web-01_ssh_key
        passphrase:
          from_secret: web-01_ssh_passphrase
        script:
          - cd /srv/docker/svelte-adminlte
          - docker-compose down
          - docker-compose pull
          - docker-compose up -d
